### ISSUE TITLE
Any chance you can introduce a stopAnimation function?

### ISSUE THREAD

**Issue by sunmer** [almond-bongbong/react-slot-counter#14]
Basically the behaviour could be that the animation is infinite until stopAnimation is called

**Comment by almond-bongbong** [comment]
Thank you for the excellent suggestion. Currently, the module is designed with simplicity in mind, focusing on basic counting animations. Due to structural limitations, implementing a stopAnimation feature would be complex within my current capabilities. However, I'll certainly consider all possible options to see if it's feasible to include this functionality in future updates.

I apologize for not being able to provide a more positive response at this time, but I truly appreciate your input and suggestion. Thank you again.
