### ISSUE TITLE
Infinite counter animation

### ISSUE THREAD

**Issue by azzztec** [almond-bongbong/react-slot-counter#40]
Is it possible to create infinite counter animation?

**Comment by almond-bongbong** [comment]
It is currently not possible to implement an infinite counter animation.

As an alternative, though not perfect, you can use dummyCharacterCount and duration to run a long-duration animation. However, due to the limitations of the current functionality, running animations for very long periods would require too many elements, leading to inefficient memory and CPU usage.

In a simple test, setting dummyCharacterCount to 2000 and duration to 100 worked, but the easing of the animation did not appear smooth for longer durations.
