### ISSUE TITLE
Sticky value

### ISSUE THREAD

**Issue by Konstantin9658** [almond-bongbong/react-slot-counter#9]
Hello, it's me again

Faced such a problem as sticking the value of the counter and sometimes (for a reason unknown to me) the numbers are located as if far from each other. I searched everything that could affect the arrangement of numbers within myself, or maybe something could arrange them in this way, but alas, without result ...

Any ideas what could be causing this?

![image_2023-06-15_12-08-39](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/691f6b3a-1e72-4153-b7ce-10e0d2aea0fc)
![image_2023-06-15_12-08-57](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/3bc19077-b32c-4dc2-bb4a-9610ce9bfaab)
![image_2023-06-15_12-09-20](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/4a161037-53dd-4d52-a830-691cf1c037af)

It also happens like this

![image](https://github.com/almond-bongbong/react-slot-counter/assets/76180339/3971a80a-0695-46c3-a3e3-1c67570eec79)

**Comment by almond-bongbong** [comment]
I understand that you've invested considerable effort in troubleshooting this issue already. My suspicion is that the issue may be related to the font or 'letter-spacing'. It could also potentially be related to the 'kerning' settings of the font you are using.

If you could share the code you're using or give access to the live environment where this issue is occurring, I could give a more detailed response. If possible, could you share a code snippet that reproduces the issue?

Looking forward to your reply to help you better.

**Comment by Konstantin9658** [comment]
@almond-bongbong  It seems I raised the fuss ahead of time, and we seem to have managed to correct the situation. Quite possibly this was due to the fact that a fixed width was set for this scoreboard, which led to such behavior. Thanks for your responsiveness
